---
name: Salt Kitchen test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  kitchen-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instances:
          - default-ubuntu-2204-30065
          - default-debian-12-30065
          - default-rocky9-30065
          - default-fedora38-30065
          - default-opensuse15-30060
          - default-ubuntu-2204-30066
          - default-debian-12-30066
          - default-rocky9-30066
          - default-fedora38-30066
          - default-ubuntu-2204-30067
          - default-debian-12-30067
          - default-rocky9-30067
          - default-fedora38-30067
          - default-ubuntu-2204-30070
          - default-debian-12-30070
          - default-rocky9-30070
          - default-fedora38-30070
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - name: Install vagrant and virtualbox
        uses: ConorMacBride/install-package@v1
        with:
          apt: vagrant virtualbox
      - name: Run kitchen test
        run: |
          bundle exec kitchen test ${{ matrix.instances }}
